repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: sh -c "cd backend && poetry run black ."
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: sh -c "cd backend && poetry run pylint **/*.py"
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: sh -c "cd backend && poetry run isort ."
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: sh -c "cd backend && poetry run mypy **/*.py"
        language: system
        types: [python]
