repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black .
        language: system
        types: [python]

      - id: pylint
        name: pylint
        entry: poetry run pylint **/*.py
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: poetry run isort .
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: sh -c "poetry run mypy --install-types && poetry run mypy **/*.py"
        language: system
        types: [python]
