services:
  app:
    build:
      dockerfile: backend/docker/Dockerfile
    ports:
      - "8000:8000"
      - "5001:5001"

  frontend:
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app

