name: Python Linters Action

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version: '3.10'

      - name: Install Poetry
        run: |
            curl -sSL https://install.python-poetry.org | python3 -
            echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: poetry install --no-root

      - name: Run Black
        run: |
            poetry run black --check --diff .  # Check formatting without making changes

      - name: Run Pylint
        run: |
            poetry run pylint **/*.py

      - name: Run isort
        run: |
            poetry run isort --diff .  # Check import sorting without making changes

      - name: Run mypy
        run: poetry run mypy **/*.py --install-types --non-interactive --verbose

      - name: Run tests
        run: poetry run tox
